name: LinkedIn OAuth Bridge

on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: 'Authorization Code from LinkedIn'
        required: true

jobs:
  exchange-and-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Exchange Authorization Code for Access Token
        env:
          CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          AUTH_CODE: ${{ github.event.inputs.auth_code }}
          REDIRECT_URI: https://YOUR_GITHUB_PAGES_URL/callback.html
        id: exchange
        run: |
          echo "Exchanging authorization code for access token..."
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=authorization_code" \
            -d "code=$AUTH_CODE" \
            -d "redirect_uri=$REDIRECT_URI" \
            -d "client_id=$CLIENT_ID" \
            -d "client_secret=$CLIENT_SECRET" \
            https://www.linkedin.com/oauth/v2/accessToken)
          echo "Response: $RESPONSE"
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" == "null" ]; then
            echo "Failed to retrieve access token"
            exit 1
          fi
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Fetch LinkedIn Profile
        env:
          ACCESS_TOKEN: ${{ env.access_token }}
        run: |
          echo "Fetching LinkedIn profile..."
          PROFILE=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
            https://api.linkedin.com/v2/me)
          echo "Profile: $PROFILE"
          echo "$PROFILE" > linkedin-profile.json

      - name: Save Profile to Repository
        uses: actions/upload-artifact@v3
        with:
          name: linkedin-profile
          path: linkedin-profile.json
