# theme: jekyll-theme-minimal
title: ASI Saga
description: Genesis of Artifical Super Intelligence (ASI)
#remote_theme: pages-themes/time-machine@v0.2.0

plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: "" # Applies to all files in your site
      type: "html" # Targets only HTML files
    values:
      layout: default # The name of the layout you want to apply
