products:

  - title: GitHub Agent
    logo: "/assets/images/github-agent.png"
    summary: "Explore the capabilities of GitHub Agent, designed to assist with your development needs seamlessly."
    url: "/realm-of-agents/github-agent/"

  - title: Purpose Driven Agent
    logo: "/assets/images/purpose-driven-agent.png"
    summary: "A perpetual, autonomous agent, that operates on the basis of purpose, rather than a specific task."
    url: "/realm-of-agents/purpose-driven-agent/"

  - title: Agent Operating System
    logo: "/assets/images/agent-operating-system.png"
    summary: "An Operating System of perpetual, autonomous agents that can be used to build any application."
    url: "/realm-of-agents/agent-operating-system/"

  - title: Business Infinity
    logo: "/assets/images/business-infinity.png"
    summary: "A cutting-edge platform for business automation, built on top of Agent Operating System, tailored to drive business growth and innovation."
    url: "/business-infinity/"

