products:

github_agent:
  title: "GitHub Agent"
  summary: "Explore the capabilities of GitHub Agent, designed to assist with your development needs seamlessly."
  image: "/assets/images/github-agent.png"
  url: "/realm-of-agents/github-agent"
  id: "github_agent"

purpose_driven_agent:
  title: "Purpose Driven Agent"
  summary: "A perpetual, autonomous agent, that operates on the basis of purpose, rather than a specific task."
  image: "/assets/images/purpose-driven-agent.png"
  url: "/realm-of-agents/purpose-driven-agent"
  id: "purpose_driven_agent"

agent_operating_system:
  title: "Agent Operating System"
  summary: "An Operating System of perpetual, autonomous agents that can be used to build any application."
  image: "/assets/images/agent-operating-system.png"
  url: "/realm-of-agents/agent-operating-system"
  id: "agent_operating_system"

business_infinity:
  title: "Business Infinity"
  summary: "A cutting-edge platform for business automation, built on top of Agent Operating System, tailored to drive business growth and innovation."
  image: "/assets/images/business-infinity.png"
  url: "/business-infinity"
  id: "business_infinity"

product1:
  title: "Product 1"
  summary: "This is Product 1."
  image: "/assets/images/product1.jpg"
  url: "/products/product1"
  id: "product1"

product2:
  title: "Product 2"
  summary: "This is Product 2."
  image: "/assets/images/product2.jpg"
  url: "/products/product2"
  id: "product2"

