name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Copy nav.yml from theme repo to site _data
      - name: Copy nav.yml from theme repo to site _data
        run: |
          cp Website/common.asisaga.com/_data/nav.yml Website/www.asisaga.com/_data/nav.yml

      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: Website/www.asisaga.com
          destination: _site
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
